// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgn4MWsLCrG3dGmj_yntVhBFts1vn9gv0',
    appId: '1:100813103355:web:4c8167391ed3c1e031d05e',
    messagingSenderId: '100813103355',
    projectId: 'expense-tracker-58f50',
    authDomain: 'expense-tracker-58f50.firebaseapp.com',
    storageBucket: 'expense-tracker-58f50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM62qbny_aubVCrVd7L_b87y-DrpeSGys',
    appId: '1:100813103355:android:fb5c93255d935a0731d05e',
    messagingSenderId: '100813103355',
    projectId: 'expense-tracker-58f50',
    storageBucket: 'expense-tracker-58f50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwawpI2gAUtf-7XRmA9VU97ikEfGKQgE0',
    appId: '1:100813103355:ios:d9ad4911dd58074231d05e',
    messagingSenderId: '100813103355',
    projectId: 'expense-tracker-58f50',
    storageBucket: 'expense-tracker-58f50.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwawpI2gAUtf-7XRmA9VU97ikEfGKQgE0',
    appId: '1:100813103355:ios:d9ad4911dd58074231d05e',
    messagingSenderId: '100813103355',
    projectId: 'expense-tracker-58f50',
    storageBucket: 'expense-tracker-58f50.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgn4MWsLCrG3dGmj_yntVhBFts1vn9gv0',
    appId: '1:100813103355:web:b769e299c7ac6bef31d05e',
    messagingSenderId: '100813103355',
    projectId: 'expense-tracker-58f50',
    authDomain: 'expense-tracker-58f50.firebaseapp.com',
    storageBucket: 'expense-tracker-58f50.firebasestorage.app',
  );
}
